### PR TITLE
Fix crashing bug in Linux

### LINKED ISSUE #75: Opening Telegram Link crashes in Linux
On the Fedora Operating System, opening the telegram link causes the application to freeze, as `Desktop.getDesktop().browse()` is not supported by linux.

### PR DESCRIPTION
**Pull request by et-irl**
Closes #75.

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 1]
```diff
@@ -85,22 +87,34 @@ public PersonCard(Person person, int displayedIndex) {
...
             // Handle the case where there is no telegram handle
             // You can show an error message or take any other action as needed
             System.out.println("No Telegram handle available.");
         }
     }
 
-
+    /**
+     * Opens a link using the default web browser on the user's system.
+     *
```
Comment (lsyurea) [inline src/main/java/seedu/address/ui/PersonCard.java:103]: I like the use of conditionals to handle the different OS!

**Review by lsyurea — APPROVED** [review]
LGTM
