### PR TITLE
Fixed saving assignment grades

### LINKED ISSUE #87: Documentation flaws with the `grade` command.
The user guide is missing the `grade` command in the command summary section at the bottom.

In `GradeCommand.java`, you should not use square brackets in the following

```java
    public static final String MESSAGE_USAGE = COMMAND_WORD
            + ": Marks the specific assignment of the student identified\n"
            + "by the index number used in the displayed student list.\n"
            + "Parameters: INDEX (must be a positive integer), "
            + "[" + PREFIX_NAME + "ASSIGNMENT_NAME] "
            + "[" + PREFIX_GRADE + "SCORE]\n"
            + "Example: " + COMMAND_WORD + " 1 n/Tutorial1 g/96 ";
```
As square brackets represent optional parameters.

In the same file, the example command is wrong, and is not `grade`.

```java
- `assign 1 n/Tutorial1 g/90`
```

### LINKED ISSUE #90: Persistency issue with grade assignment
Important to ensure that grades for assignments are remembered.

### PR DESCRIPTION
**Pull request by Vanessamae23**
Closes #90 
Closes #87 

Fix the UI as well for bigger fonts and changed logo
Added some testing for json

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AssignmentCommand.java [hunk 1]
```diff
@@ -24,9 +24,8 @@ public class AssignmentCommand extends Command {
     public static final String MESSAGE_FAIL = "Assignment not created.";
     public static final String MESSAGE_USAGE = COMMAND_WORD
         + ": Creates an assignment for all students.\n"
-        + "Parameters: "
-        + "[" + PREFIX_NAME + "ASSIGNMENT_NAME] "
-        + "[" + PREFIX_MAX_SCORE + "MAX_SCORE] "
+        + "Compulsory Parameters: "
+        + PREFIX_NAME + "ASSIGNMENT_NAME " + PREFIX_MAX_SCORE + "MAX_SCORE "
```
Comment (lsyurea) [inline src/main/java/seedu/address/logic/commands/AssignmentCommand.java:28]: Nice to see that the docs adhere to the user guide of optional vs compulsory parameters.

File: src/main/resources/view/MainWindow.fxml [hunk 2]
```diff
@@ -27,8 +28,10 @@
         <URL value="@Extensions.css" />
       </stylesheets>
       <VBox>
-        <HBox VBox.vgrow="ALWAYS" style="-fx-background-color: #1194f0;">
-          <Label text="npc_track" styleClass="title-header" HBox.hgrow="ALWAYS"/>
+        <HBox style="-fx-background-color: #1194f0;">
+          <ImageView fitHeight="150" preserveRatio="true">
```
Comment (lsyurea) [inline src/main/resources/view/MainWindow.fxml:32]: Cool image for the UI.

File: src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java [hunk 3]
```diff
@@ -32,7 +34,13 @@ public class JsonAdaptedPersonTest {
     private static final List<JsonAdaptedTag> VALID_TAGS = BENSON.getTags().stream()
             .map(JsonAdaptedTag::new)
             .collect(Collectors.toList());
+    private static final List<JsonAdaptedAssignment> VALID_ASSIGNMENTS = BENSON.getAssignments().stream()
```
Comment (lsyurea) [inline src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java:37]: Nice to see that the collect solves the issue of persistency.

File: src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java [hunk 4]
```diff
@@ -77,15 +85,15 @@ public void toModelType_nullPhone_throwsIllegalValueException() {
...
+                        VALID_TELEGRAM_HANDLE, VALID_ATTENDANCE, VALID_TAGS, VALID_COMMENTS, VALID_ASSIGNMENTS);
         String expectedMessage = Email.MESSAGE_CONSTRAINTS;
         assertThrows(IllegalValueException.class, expectedMessage, person::toModelType);
     }
 
     @Test
     public void toModelType_nullEmail_throwsIllegalValueException() {
         JsonAdaptedPerson person = new JsonAdaptedPerson(VALID_NAME, VALID_PHONE, null,
-                VALID_TELEGRAM_HANDLE, VALID_ATTENDANCE, VALID_TAGS);
+                VALID_TELEGRAM_HANDLE, VALID_ATTENDANCE, VALID_TAGS, VALID_COMMENTS, VALID_ASSIGNMENTS);
```
Comment (lsyurea) [inline src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java:96]: Nice to see the test cases updated as well.

**Review by lsyurea — APPROVED** [review]
LGTM
